// exerciseData.js
export const exerciseData = [
  {
    id: 1,
    name: "Push-ups",
    category: "Upper Body",
    mainMuscles: ["Chest", "Shoulders", "Triceps"],
    benefits: [
      "Builds upper body strength",
      "Improves core stability",
      "Enhances posture",
    ],
    steps: [
      "Start in a plank position with hands shoulder-width apart",
      "Lower your body until chest nearly touches the ground",
      "Keep your core tight and body in a straight line",
      "Push back up to the starting position",
    ],
    tips: [
      "Keep your elbows close to your body",
      "Don't let your hips sag",
      "Breathe steadily throughout the movement",
    ],
    difficulty: "Beginner",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=IODxDxX7oi4",
  },
  {
    id: 2,
    name: "Pull-Ups",
    category: "Upper Body",
    mainMuscles: ["Back", "Biceps", "Shoulders"],
    benefits: [
      "Develops upper body strength",
      "Improves grip strength",
      "Builds back muscle definition",
    ],
    steps: [
      "Grip the pull-up bar with hands slightly wider than shoulders",
      "Hang with arms fully extended",
      "Pull yourself up until chin passes the bar",
      "Lower back down with control",
    ],
    tips: [
      "Avoid swinging or kipping",
      "Engage your core throughout",
      "Focus on squeezing your back muscles",
    ],
    difficulty: "Intermediate",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=eGo4IYlbE5g",
  },
  {
    id: 3,
    name: "Sit-Ups",
    category: "Core",
    mainMuscles: ["Abdominals", "Hip Flexors"],
    benefits: [
      "Strengthens core muscles",
      "Improves posture",
      "Enhances abdominal endurance",
    ],
    steps: [
      "Lie on your back with knees bent",
      "Place hands behind your head",
      "Lift your upper body off the ground",
      "Lower back down with control",
    ],
    tips: [
      "Don't pull on your neck",
      "Keep lower back pressed against the ground",
      "Exhale as you lift up",
    ],
    difficulty: "Beginner",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=jDwoBqPH0jk",
  },
  {
    id: 4,
    name: "Squats",
    category: "Lower Body",
    mainMuscles: ["Quadriceps", "Hamstrings", "Glutes"],
    benefits: [
      "Builds lower body strength",
      "Improves balance and stability",
      "Enhances functional movement",
    ],
    steps: [
      "Stand with feet shoulder-width apart",
      "Lower your body as if sitting back into a chair",
      "Keep chest up and core engaged",
      "Push through heels to return to standing",
    ],
    tips: [
      "Keep knees aligned with toes",
      "Maintain neutral spine",
      "Don't let knees cave inward",
    ],
    difficulty: "Beginner",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=aclHkVaku9U",
  },
  {
    id: 5,
    name: "Lunges",
    category: "Lower Body",
    mainMuscles: ["Quadriceps", "Hamstrings", "Glutes"],
    benefits: [
      "Improves balance and stability",
      "Develops leg strength",
      "Enhances core control",
    ],
    steps: [
      "Stand with feet hip-width apart",
      "Step forward with one leg",
      "Lower back knee toward ground",
      "Push off front foot to return to start",
    ],
    tips: [
      "Keep upper body straight",
      "Don't let front knee extend past toes",
      "Land softly with each step",
    ],
    difficulty: "Beginner",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=QOVaHwm-Q6U",
  },
  {
    id: 6,
    name: "Plank",
    category: "Core",
    mainMuscles: ["Core", "Shoulders", "Back"],
    benefits: [
      "Strengthens core muscles",
      "Improves posture",
      "Develops stability",
    ],
    steps: [
      "Start in push-up position",
      "Rest on forearms with elbows under shoulders",
      "Keep body in straight line",
      "Hold position for desired duration",
    ],
    tips: [
      "Don't let hips sag",
      "Keep neck neutral",
      "Breathe steadily throughout",
    ],
    difficulty: "Beginner",
    estimatedTime: "1-5 minutes",
    videoUrl: "https://youtube.com/watch?v=pSHjTRCQxIw",
  },
  {
    id: 7,
    name: "Burpees",
    category: "Full Body",
    mainMuscles: ["Legs", "Chest", "Core"],
    benefits: [
      "Burns calories effectively",
      "Improves cardiovascular fitness",
      "Builds full-body strength",
    ],
    steps: [
      "Start standing, drop to a squat position",
      "Kick feet back to plank position",
      "Perform a push-up",
      "Jump feet forward and explosively jump up",
    ],
    tips: [
      "Maintain proper form throughout",
      "Scale intensity as needed",
      "Land softly on jumps",
    ],
    difficulty: "Advanced",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=dZgVxmf6jkA",
  },
  {
    id: 8,
    name: "Mountain Climbers",
    category: "Core",
    mainMuscles: ["Core", "Shoulders", "Hip Flexors"],
    benefits: [
      "Improves core strength",
      "Enhances cardio endurance",
      "Develops coordination",
    ],
    steps: [
      "Start in plank position",
      "Alternate bringing knees to chest",
      "Keep hips level throughout",
      "Maintain quick, controlled pace",
    ],
    tips: ["Keep core engaged", "Don't bounce hips", "Breathe rhythmically"],
    difficulty: "Intermediate",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=nmwgirgXLYM",
  },
  {
    id: 9,
    name: "Jumping Jacks",
    category: "Cardio",
    mainMuscles: ["Full Body", "Shoulders", "Calves"],
    benefits: [
      "Improves cardiovascular fitness",
      "Enhances coordination",
      "Warms up full body",
    ],
    steps: [
      "Start standing with feet together",
      "Jump feet apart while raising arms",
      "Jump feet back together while lowering arms",
      "Maintain rhythm and flow",
    ],
    tips: [
      "Land softly",
      "Keep movements controlled",
      "Maintain steady breathing",
    ],
    difficulty: "Beginner",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=c4DAnQ6DtF8",
  },
  {
    id: 10,
    name: "Crunches",
    category: "Core",
    mainMuscles: ["Abdominals"],
    benefits: [
      "Strengthens core muscles",
      "Improves abdominal definition",
      "Enhances core stability",
    ],
    steps: [
      "Lie on back with knees bent",
      "Place hands behind head",
      "Lift shoulders off ground",
      "Lower back with control",
    ],
    tips: [
      "Don't pull on neck",
      "Focus on abdominal contraction",
      "Maintain controlled movement",
    ],
    difficulty: "Beginner",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=Xyd_fa5zoEU",
  },
  {
    id: 11,
    name: "Bicep Curls",
    category: "Upper Body",
    mainMuscles: ["Biceps", "Forearms"],
    benefits: [
      "Builds arm strength",
      "Improves grip strength",
      "Enhances arm definition",
    ],
    steps: [
      "Stand with dumbbells at sides, palms forward",
      "Keeping elbows close to body, curl weights up",
      "Pause briefly at the top",
      "Lower weights with control",
    ],
    tips: [
      "Avoid swinging motions",
      "Keep upper arms stationary",
      "Maintain controlled movement",
    ],
    difficulty: "Beginner",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=ykJmrZ5v0Oo",
  },
  {
    id: 12,
    name: "Tricep Dips",
    category: "Upper Body",
    mainMuscles: ["Triceps", "Chest", "Shoulders"],
    benefits: [
      "Strengthens triceps",
      "Improves upper body stability",
      "Enhances pushing strength",
    ],
    steps: [
      "Place hands on edge of bench or chair",
      "Lower body with control",
      "Keep elbows pointing backward",
      "Push back up to starting position",
    ],
    tips: [
      "Keep elbows close to body",
      "Don't let shoulders roll forward",
      "Maintain steady pace",
    ],
    difficulty: "Intermediate",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=6kALZikXxLc",
  },
  {
    id: 13,
    name: "Deadlifts",
    category: "Full Body",
    mainMuscles: ["Back", "Hamstrings", "Glutes"],
    benefits: [
      "Builds overall strength",
      "Improves posture",
      "Enhances core stability",
    ],
    steps: [
      "Stand with feet hip-width apart",
      "Hinge at hips to grip bar",
      "Keep back straight, chest up",
      "Stand up straight, then lower with control",
    ],
    tips: [
      "Maintain neutral spine",
      "Keep bar close to body",
      "Breathe properly throughout",
    ],
    difficulty: "Advanced",
    estimatedTime: "15-20 minutes",
    videoUrl: "https://youtube.com/watch?v=op9kVnSso6Q",
  },
  {
    id: 14,
    name: "Bench Press",
    category: "Upper Body",
    mainMuscles: ["Chest", "Shoulders", "Triceps"],
    benefits: [
      "Builds chest strength",
      "Improves pushing power",
      "Develops upper body",
    ],
    steps: [
      "Lie on bench with feet flat",
      "Grip bar slightly wider than shoulders",
      "Lower bar to chest with control",
      "Press bar up to starting position",
    ],
    tips: [
      "Keep wrists straight",
      "Maintain proper arch",
      "Use spotter when needed",
    ],
    difficulty: "Intermediate",
    estimatedTime: "15-20 minutes",
    videoUrl: "https://youtube.com/watch?v=rT7DgCr-3pg",
  },
  {
    id: 15,
    name: "Overhead Press",
    category: "Upper Body",
    mainMuscles: ["Shoulders", "Triceps", "Upper Back"],
    benefits: [
      "Builds shoulder strength",
      "Improves stability",
      "Enhances core control",
    ],
    steps: [
      "Stand with feet shoulder-width apart",
      "Hold weights at shoulder height",
      "Press weights overhead",
      "Lower with control to start",
    ],
    tips: ["Keep core tight", "Don't arch back", "Breathe steadily"],
    difficulty: "Intermediate",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=2yjwXTZQDDI",
  },
  {
    id: 16,
    name: "Dumbbell Rows",
    category: "Upper Body",
    mainMuscles: ["Back", "Biceps", "Shoulders"],
    benefits: [
      "Strengthens back muscles",
      "Improves posture",
      "Builds arm strength",
    ],
    steps: [
      "Lean on bench with one knee and hand",
      "Hold dumbbell with free hand",
      "Pull weight up to chest",
      "Lower with control",
    ],
    tips: [
      "Keep back straight",
      "Squeeze shoulder blade",
      "Maintain stable position",
    ],
    difficulty: "Beginner",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=pYcpY20QaE8",
  },
  {
    id: 17,
    name: "Leg Press",
    category: "Lower Body",
    mainMuscles: ["Quadriceps", "Hamstrings", "Glutes"],
    benefits: [
      "Builds leg strength",
      "Develops lower body power",
      "Low impact on spine",
    ],
    steps: [
      "Sit in machine with feet shoulder-width",
      "Lower weight with control",
      "Push through heels",
      "Return to start position",
    ],
    tips: [
      "Don't lock knees at top",
      "Keep lower back against seat",
      "Maintain controlled movement",
    ],
    difficulty: "Intermediate",
    estimatedTime: "15-20 minutes",
    videoUrl: "https://youtube.com/watch?v=IZxyjW7MPJQ",
  },
  {
    id: 18,
    name: "Calf Raises",
    category: "Lower Body",
    mainMuscles: ["Calves"],
    benefits: [
      "Strengthens calf muscles",
      "Improves ankle stability",
      "Enhances lower leg power",
    ],
    steps: [
      "Stand on edge of step",
      "Lower heels below platform",
      "Rise up onto toes",
      "Lower back with control",
    ],
    tips: [
      "Keep movements controlled",
      "Don't bounce at bottom",
      "Maintain balance",
    ],
    difficulty: "Beginner",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=gwLzBJYoWlI",
  },
  {
    id: 19,
    name: "Chest Fly",
    category: "Upper Body",
    mainMuscles: ["Chest", "Shoulders"],
    benefits: [
      "Improves chest definition",
      "Enhances shoulder mobility",
      "Builds pressing strength",
    ],
    steps: [
      "Lie on bench with dumbbells above chest",
      "Lower weights out to sides",
      "Keep slight bend in elbows",
      "Bring weights back together",
    ],
    tips: [
      "Don't overstretch",
      "Maintain controlled movement",
      "Keep core engaged",
    ],
    difficulty: "Intermediate",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=eozdVDA78K0",
  },
  {
    id: 20,
    name: "Lat Pulldown",
    category: "Upper Body",
    mainMuscles: ["Back", "Biceps", "Shoulders"],
    benefits: [
      "Builds back width",
      "Improves posture",
      "Strengthens pulling muscles",
    ],
    steps: [
      "Sit at machine, grip bar wide",
      "Pull bar down to chest",
      "Keep chest up throughout",
      "Return with control",
    ],
    tips: [
      "Don't lean back excessively",
      "Keep shoulders down",
      "Focus on back muscles",
    ],
    difficulty: "Beginner",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=CAwf7n6Luuc",
  },

  // Exercises 21-30
  {
    id: 21,
    name: "Seated Row",
    category: "Upper Body",
    mainMuscles: ["Back", "Biceps", "Shoulders"],
    benefits: [
      "Improves posture",
      "Strengthens back muscles",
      "Builds arm strength",
    ],
    steps: [
      "Sit at row machine, feet on platform",
      "Grip handles with straight arms",
      "Pull handles to torso",
      "Return with control",
    ],
    tips: [
      "Keep back straight",
      "Don't round shoulders",
      "Squeeze shoulder blades",
    ],
    difficulty: "Beginner",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=GZbfZ033f74",
  },
  {
    id: 22,
    name: "Treadmill Running",
    category: "Cardio",
    mainMuscles: ["Legs", "Core", "Full Body"],
    benefits: [
      "Improves cardiovascular health",
      "Burns calories",
      "Builds endurance",
    ],
    steps: [
      "Start at walking pace to warm up",
      "Gradually increase speed",
      "Maintain proper running form",
      "Cool down gradually",
    ],
    tips: ["Keep good posture", "Land midfoot", "Swing arms naturally"],
    difficulty: "Beginner to Advanced",
    estimatedTime: "20-30 minutes",
    videoUrl: "https://youtube.com/watch?v=YpUwz9jRJuE",
  },
  {
    id: 23,
    name: "Cycling",
    category: "Cardio",
    mainMuscles: ["Legs", "Core"],
    benefits: [
      "Low impact cardio",
      "Builds leg strength",
      "Improves endurance",
    ],
    steps: [
      "Adjust seat height properly",
      "Start pedaling at moderate pace",
      "Maintain steady rhythm",
      "Adjust resistance as needed",
    ],
    tips: [
      "Keep proper posture",
      "Don't bounce in seat",
      "Maintain smooth pedaling",
    ],
    difficulty: "Beginner",
    estimatedTime: "20-45 minutes",
    videoUrl: "https://youtube.com/watch?v=bPuPYk_6e8g",
  },
  {
    id: 24,
    name: "Elliptical Training",
    category: "Cardio",
    mainMuscles: ["Full Body"],
    benefits: [
      "Low impact cardio",
      "Full body workout",
      "Improves coordination",
    ],
    steps: [
      "Step onto machine safely",
      "Start with steady pace",
      "Use handles for upper body",
      "Maintain smooth motion",
    ],
    tips: [
      "Keep good posture",
      "Don't lean on handles",
      "Push and pull with arms",
    ],
    difficulty: "Beginner",
    estimatedTime: "20-30 minutes",
    videoUrl: "https://youtube.com/watch?v=mTh6UKA0L3A",
  },
  {
    id: 25,
    name: "Swimming",
    category: "Cardio",
    mainMuscles: ["Full Body"],
    benefits: [
      "Full body workout",
      "Zero impact exercise",
      "Improves cardiovascular health",
    ],
    steps: [
      "Start with basic stroke",
      "Maintain proper breathing",
      "Keep body streamlined",
      "Coordinate arms and legs",
    ],
    tips: ["Breathe rhythmically", "Stay relaxed", "Focus on form"],
    difficulty: "Intermediate",
    estimatedTime: "30-45 minutes",
    videoUrl: "https://youtube.com/watch?v=pFN2n7CRqhw",
  },
  {
    id: 26,
    name: "Box Jumps",
    category: "Plyometrics",
    mainMuscles: ["Legs", "Core"],
    benefits: [
      "Builds explosive power",
      "Improves coordination",
      "Enhances leg strength",
    ],
    steps: [
      "Stand facing box at appropriate height",
      "Jump onto box with both feet",
      "Land softly in squat position",
      "Step back down carefully",
    ],
    tips: ["Land softly", "Use arms for momentum", "Start with lower height"],
    difficulty: "Advanced",
    estimatedTime: "10-15 minutes",
    videoUrl: "https://youtube.com/watch?v=52r_Ul5k03g",
  },
  {
    id: 27,
    name: "Russian Twists",
    category: "Core",
    mainMuscles: ["Obliques", "Core"],
    benefits: ["Strengthens core", "Improves rotation", "Targets love handles"],
    steps: [
      "Sit with knees bent, feet off ground",
      "Lean back slightly, keep back straight",
      "Rotate torso side to side",
      "Hold weight for added difficulty",
    ],
    tips: ["Keep chest up", "Move slowly and controlled", "Don't strain neck"],
    difficulty: "Intermediate",
    estimatedTime: "5-10 minutes",
    videoUrl: "https://youtube.com/watch?v=wkD8rjkodUI",
  },
  {
    id: 28,
    name: "Side Plank",
    category: "Core",
    mainMuscles: ["Obliques", "Shoulders"],
    benefits: ["Strengthens core", "Improves stability", "Works obliques"],
    steps: [
      "Lie on side, prop up on forearm",
      "Raise hips off ground",
      "Hold position",
      "Keep body straight",
    ],
    tips: ["Keep body aligned", "Don't let hips sag", "Breathe steadily"],
    difficulty: "Intermediate",
    estimatedTime: "3-5 minutes",
    videoUrl: "https://youtube.com/watch?v=rCxF2nG9vQ0",
  },
  {
    id: 29,
    name: "Jump Rope",
    category: "Cardio",
    mainMuscles: ["Calves", "Shoulders", "Core"],
    benefits: ["Improves coordination", "Burns calories", "Enhances footwork"],
    steps: [
      "Hold rope handles at hip height",
      "Jump with small bounces",
      "Keep elbows close to body",
      "Land softly on balls of feet",
    ],
    tips: ["Stay light on feet", "Keep jumps small", "Maintain rhythm"],
    difficulty: "Beginner",
    estimatedTime: "10-20 minutes",
    videoUrl: "https://youtube.com/watch?v=FJmRQ5iTXKE",
  },
];
